apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-e6kd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-e6kd@sha256:f99c9070bdaeb5a7bd61010b30954589721a6a9937437505ca9c1c3a7d728ff9
        name: my-nodejs
        resources: {}
status: {}
